import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ClassInfo, Learner } from '@/types';
import { GradeSymbol, getGradeSymbol } from './grading';
import { format } from 'date-fns';

// Helper to add a single learner report page to a doc
const addLearnerReportPage = (
  doc: jsPDF,
  learner: Learner,
  classInfo: { subject: string; grade: string; className: string },
  gradingScheme: GradeSymbol[],
  schoolName: string,
  teacherName: string,
  schoolLogo: string | null
) => {
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;

  // Header Border
  doc.setDrawColor(41, 37, 36);
  doc.setLineWidth(1);
  doc.rect(margin, margin, pageWidth - (margin * 2), 257); // Page border

  // Logo if available
  if (schoolLogo) {
     try {
       const logoSize = 30;
       const logoX = (pageWidth - logoSize) / 2;
       doc.addImage(schoolLogo, 'PNG', logoX, 30, logoSize, logoSize);
     } catch (e) {}
  }

  // Header
  const textStartY = schoolLogo ? 70 : 40;
  
  doc.setFontSize(24);
  doc.setTextColor(41, 37, 36);
  doc.setFont("helvetica", "bold");
  doc.text(schoolName, pageWidth / 2, textStartY, { align: 'center' });
  
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("Learner Performance Report", pageWidth / 2, textStartY + 10, { align: 'center' });

  // Divider
  doc.setDrawColor(200);
  doc.line(margin + 20, textStartY + 20, pageWidth - (margin + 20), textStartY + 20);

  // Student Info
  const startY = textStartY + 40;
  doc.setFontSize(12);
  doc.setTextColor(80);
  doc.text("Learner Name:", margin + 20, startY);
  doc.text("Grade:", margin + 20, startY + 10);
  doc.text("Class:", margin + 20, startY + 20);
  doc.text("Subject:", margin + 20, startY + 30);
  if (teacherName) {
    doc.text("Teacher:", margin + 20, startY + 40);
  }

  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.text(learner.name, margin + 60, startY);
  doc.text(classInfo.grade, margin + 60, startY + 10);
  doc.text(classInfo.className, margin + 60, startY + 20);
  doc.text(classInfo.subject, margin + 60, startY + 30);
  if (teacherName) {
    doc.text(teacherName, margin + 60, startY + 40);
  }

  // Result Section
  const resultY = startY + 60;
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(margin + 10, resultY, pageWidth - (margin * 2) - 20, 50, 3, 3, 'F');
  
  const symbolObj = getGradeSymbol(learner.mark, gradingScheme);
  
  doc.setFontSize(16);
  doc.setTextColor(80);
  doc.setFont("helvetica", "normal");
  doc.text("Mark Achieved", pageWidth / 2, resultY + 15, { align: 'center' });
  
  doc.setFontSize(32);
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.text(`${learner.mark ? learner.mark + '%' : 'N/A'}`, pageWidth / 2, resultY + 30, { align: 'center' });

  if (symbolObj) {
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.setFont("helvetica", "normal");
    doc.text(`Symbol: ${symbolObj.symbol}   |   Level: ${symbolObj.level}`, pageWidth / 2, resultY + 42, { align: 'center' });
  }

  // Comments Section
  const commentY = resultY + 70;
  doc.setFontSize(14);
  doc.setTextColor(41, 37, 36);
  doc.setFont("helvetica", "bold");
  doc.text("Teacher's Comments", margin + 20, commentY);

  doc.setFontSize(11);
  doc.setTextColor(60);
  doc.setFont("helvetica", "italic");
  
  const comment = learner.comment || "No comment recorded.";
  const splitComment = doc.splitTextToSize(comment, pageWidth - (margin * 2) - 40);
  doc.text(splitComment, margin + 20, commentY + 10);

  // Footer Signature
  const footerY = 240;
  doc.setDrawColor(150);
  doc.setLineWidth(0.5);
  doc.line(margin + 20, footerY, margin + 80, footerY); // Signature line
  doc.line(pageWidth - margin - 80, footerY, pageWidth - margin - 20, footerY); // Date line
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.setFont("helvetica", "normal");
  doc.text("Teacher Signature", margin + 20, footerY + 5);
  doc.text("Date", pageWidth - margin - 80, footerY + 5);
  
  doc.text("Generated by SmaReg", pageWidth / 2, 270, { align: 'center' });
};

export const generateClassPDF = (
  classInfo: ClassInfo, 
  gradingScheme: GradeSymbol[], 
  schoolName: string = "My School", 
  teacherName: string = "",
  schoolLogo: string | null = null
) => {
  const doc = new jsPDF();

  // Document Configuration
  const pageWidth = doc.internal.pageSize.width;
  const margin = 14;

  // Logo Logic
  if (schoolLogo) {
    try {
      doc.addImage(schoolLogo, 'PNG', margin, 10, 25, 25);
    } catch (e) {
      console.warn("Failed to add logo to PDF", e);
    }
  }
  
  // Header Section
  doc.setFontSize(22);
  doc.setTextColor(40);
  
  // Align school name next to logo if exists, else left
  const textX = schoolLogo ? margin + 30 : margin;
  doc.text(schoolName, textX, 22);

  doc.setFontSize(14);
  doc.setTextColor(100);
  doc.text("Class Performance Report", textX, 30);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  const dateStr = format(new Date(), 'PPP');
  doc.text(`Generated on: ${dateStr}`, textX, 36);
  
  if (teacherName) {
    doc.text(`Teacher: ${teacherName}`, pageWidth - margin - doc.getTextWidth(`Teacher: ${teacherName}`), 22);
  }

  // Class Details Box
  const startY = 48; // Shifted down slightly to accommodate logo area if needed
  doc.setDrawColor(200);
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(margin, startY, pageWidth - (margin * 2), 24, 2, 2, 'FD');

  doc.setFontSize(10);
  doc.setTextColor(80);
  doc.text("Subject:", margin + 5, startY + 8);
  doc.text("Class Name:", margin + 5, startY + 16);
  doc.text("Grade:", margin + 80, startY + 8);
  doc.text("Total Learners:", margin + 80, startY + 16);

  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.text(classInfo.subject, margin + 25, startY + 8);
  doc.text(classInfo.className, margin + 25, startY + 16);
  doc.text(classInfo.grade, margin + 95, startY + 8);
  doc.text(classInfo.learners.length.toString(), margin + 110, startY + 16);

  // Stats Calculation
  const marks = classInfo.learners
    .map(l => parseFloat(l.mark))
    .filter(m => !isNaN(m));
  
  const average = marks.length > 0 
    ? (marks.reduce((a, b) => a + b, 0) / marks.length).toFixed(1) 
    : "N/A";
  
  const passCount = marks.filter(m => m >= 50).length;
  const passRate = marks.length > 0 
    ? Math.round((passCount / marks.length) * 100) 
    : 0;

  // Stats in Header
  doc.setFontSize(10);
  doc.setTextColor(80);
  doc.setFont("helvetica", "normal");
  doc.text("Average:", margin + 140, startY + 8);
  doc.text("Pass Rate:", margin + 140, startY + 16);

  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.text(`${average}%`, margin + 160, startY + 8);
  doc.text(`${passRate}%`, margin + 160, startY + 16);

  // Table Data
  const tableRows = classInfo.learners.map((learner, index) => {
    const symbolObj = getGradeSymbol(learner.mark, gradingScheme);
    return [
      index + 1,
      learner.name,
      learner.mark ? `${learner.mark}%` : '-',
      symbolObj ? symbolObj.symbol : '-',
      symbolObj ? `L${symbolObj.level}` : '-',
      learner.comment || '-'
    ];
  });

  // Generate Table
  autoTable(doc, {
    startY: startY + 30,
    head: [['#', 'Learner Name', 'Mark', 'Symbol', 'Level', 'Comment']],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [41, 37, 36], // Dark gray (stone-800)
      textColor: 255,
      fontSize: 10,
      fontStyle: 'bold',
      halign: 'left'
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 50, fontStyle: 'bold' },
      2: { cellWidth: 20, halign: 'right' },
      3: { cellWidth: 20, halign: 'center' },
      4: { cellWidth: 15, halign: 'center' },
      5: { cellWidth: 'auto', fontStyle: 'italic' }
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
      overflow: 'linebreak'
    },
    alternateRowStyles: {
      fillColor: [250, 250, 249] // Very light gray (stone-50)
    },
    margin: { top: 65, right: margin, bottom: 20, left: margin },
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
    doc.text(
      schoolName,
      margin,
      doc.internal.pageSize.height - 10,
      { align: 'left' }
    );
  }

  // Save
  doc.save(`${classInfo.className}_${classInfo.subject}_Report.pdf`);
};

export const generateBlankClassListPDF = (
  classInfo: ClassInfo,
  schoolName: string = "My School", 
  teacherName: string = "",
  schoolLogo: string | null = null
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const margin = 14;

  // Header Logic with Logo
  const textX = schoolLogo ? margin + 30 : margin;
  if (schoolLogo) {
    try {
      doc.addImage(schoolLogo, 'PNG', margin, 10, 25, 25);
    } catch (e) {}
  }

  // Header
  doc.setFontSize(18);
  doc.setTextColor(40);
  doc.text("Mark Recording Sheet", textX, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(schoolName, textX, 26);

  // Context Info
  const startY = 40;
  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.text(`Subject: ${classInfo.subject}`, margin, startY);
  doc.text(`Class: ${classInfo.className}`, margin + 80, startY);
  doc.text(`Grade: ${classInfo.grade}`, margin + 140, startY);
  
  if (teacherName) {
    doc.text(`Teacher: ${teacherName}`, margin, startY + 6);
  }

  doc.text(`Date: _______________________`, margin + 80, startY + 6);
  doc.text(`Task: _______________________`, margin + 140, startY + 6);

  // Table Data (Just names and empty columns)
  const tableRows = classInfo.learners.map((learner, index) => [
    index + 1,
    learner.name,
    '', // Mark
    '', // Comment
  ]);

  // Generate Table
  autoTable(doc, {
    startY: startY + 15,
    head: [['#', 'Learner Name', 'Mark / Score', 'Notes / Comments']],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [240, 240, 240],
      textColor: 40,
      lineColor: 200,
      lineWidth: 0.1,
      fontSize: 10,
      fontStyle: 'bold'
    },
    styles: {
      fontSize: 10,
      cellPadding: 4,
      lineColor: 200,
      lineWidth: 0.1,
      minCellHeight: 10 // Extra height for writing
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 80, fontStyle: 'bold' },
      2: { cellWidth: 30 },
      3: { cellWidth: 'auto' }
    },
    margin: { top: 60, right: margin, bottom: 20, left: margin },
  });

  doc.save(`${classInfo.className}_BlankList.pdf`);
};

export const generateLearnerReportPDF = (
  learner: Learner,
  classInfo: { subject: string; grade: string; className: string },
  gradingScheme: GradeSymbol[],
  schoolName: string = "My School",
  teacherName: string = "",
  schoolLogo: string | null = null
) => {
  const doc = new jsPDF();
  addLearnerReportPage(doc, learner, classInfo, gradingScheme, schoolName, teacherName, schoolLogo);
  doc.save(`${learner.name}_Report.pdf`);
};

export const generateBulkLearnerReportsPDF = (
  learners: Learner[],
  classInfo: { subject: string; grade: string; className: string },
  gradingScheme: GradeSymbol[],
  schoolName: string = "My School",
  teacherName: string = "",
  schoolLogo: string | null = null
) => {
  const doc = new jsPDF();
  
  learners.forEach((learner, index) => {
    if (index > 0) doc.addPage();
    addLearnerReportPage(doc, learner, classInfo, gradingScheme, schoolName, teacherName, schoolLogo);
  });

  doc.save(`${classInfo.className}_All_Reports.pdf`);
};