"use client";

import { useState, useEffect, useRef } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { 
    Download, 
    Loader2, 
    AlertTriangle, 
    Save,
    CheckCircle2,
    Plus,
    Trash2,
    Table as TableIcon,
    BrainCircuit,
    Info,
    Rocket,
    LayoutGrid,
    Lightbulb,
    Check
} from 'lucide-react';
import { Assessment, Learner, DiagnosticRow, FullDiagnostic } from '@/lib/types';
import { useQuestionAnalysis } from '@/hooks/useQuestionAnalysis';
import { useSettings } from '@/context/SettingsContext';
import { useRemediation } from '@/hooks/useRemediation';
import { generateQuestionDiagnosticPDF } from '@/utils/pdf/questionDiagnosticReport';
import { showSuccess, showError } from '@/utils/toast';
import { cn } from '@/lib/utils';

interface QuestionDiagnosticDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  assessment: Assessment;
  learners: Learner[];
}

export const QuestionDiagnosticDialog = ({ open, onOpenChange, assessment, learners }: QuestionDiagnosticDialogProps) => {
  const { stats, loading, saveDiagnostic, generateAIAnalysis } = useQuestionAnalysis(assessment, learners);
  const { schoolName, teacherName, schoolLogo, contactEmail, contactPhone } = useSettings();
  const { activateInterventions } = useRemediation(assessment.class_id, assessment.term_id);
  
  const [rows, setRows] = useState<DiagnosticRow[]>([]);
  const [themes, setThemes] = useState<string[]>([]);
  const [overallInterventions, setOverallInterventions] = useState<string[]>([]);

  const [isExporting, setIsExporting] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isGeneratingAI, setIsGeneratingAI] = useState(false);
  const [isActivating, setIsActivating] = useState(false);
  
  const initializedRef = useRef(false);

  useEffect(() => {
    if (stats && !initializedRef.current) {
        let loadedRows: DiagnosticRow[] = [];
        let loadedThemes: string[] = [];
        let loadedOverallInt: string[] = [];
        
        if (stats.savedDiagnostic?.findings) {
            try {
                const parsed = JSON.parse(stats.savedDiagnostic.findings);
                loadedRows = Array.isArray(parsed) ? parsed : stats.initialRows;
            } catch (e) {
                loadedRows = stats.initialRows;
            }
        } else {
            loadedRows = stats.initialRows;
        }

        if (stats.savedDiagnostic?.interventions) {
            try {
                const parsed = JSON.parse(stats.savedDiagnostic.interventions);
                loadedThemes = parsed.themes || [];
                loadedOverallInt = parsed.interventions || [];
            } catch (e) {}
        }

        setRows(loadedRows);
        setThemes(loadedThemes);
        setOverallInterventions(loadedOverallInt);
        initializedRef.current = true;
    }
  }, [stats]);

  useEffect(() => {
      if (!open) {
          initializedRef.current = false;
      }
  }, [open, assessment.id]);

  const handleUpdateRow = (id: string, field: keyof DiagnosticRow, value: any) => {
      setRows(prev => prev.map(r => r.id === id ? { ...r, [field]: value } : r));
  };

  const handleDeleteRow = (id: string) => {
      setRows(prev => prev.filter(r => r.id !== id));
  };

  const handleSave = async () => {
    setIsSaving(true);
    await saveDiagnostic({
        rows,
        overall_class_themes: themes,
        overall_interventions: overallInterventions
    });
    setIsSaving(false);
  };

  const handleRunAI = async () => {
      setIsGeneratingAI(true);
      try {
          const classMeta = learners[0]?.class_id ? await (async () => {
              const cls = await (window as any).db.classes.get(learners[0].class_id);
              return { subject: cls?.subject, grade: cls?.grade };
          })() : { subject: "General", grade: "N/A" };

          const fullDiag = await generateAIAnalysis(classMeta.subject, classMeta.grade);
          if (fullDiag) {
              setRows(fullDiag.rows);
              setThemes(fullDiag.overall_class_themes);
              setOverallInterventions(fullDiag.overall_interventions);
              showSuccess("Differentiated diagnostic generated by AI.");
          }
      } finally {
          setIsGeneratingAI(false);
      }
  };

  const handleActivatePlan = async () => {
      setIsActivating(true);
      try {
          const interventions = rows.flatMap(r => 
              r.targeted_interventions
                .filter(i => i.trim())
                .map(i => ({ title: r.question, description: i.trim() }))
          );
          
          // Add themes as high-level items
          themes.forEach(t => interventions.push({ title: "Class Theme", description: t }));

          if (interventions.length === 0) {
              showError("No interventions found to activate.");
              return;
          }

          await activateInterventions(assessment.id, interventions);
      } finally {
          setIsActivating(false);
      }
  };

  const handleExport = () => {
    if (!stats) return;
    setIsExporting(true);
    try {
        generateQuestionDiagnosticPDF(
            assessment,
            learners,
            stats.qStats,
            stats.rawMarks,
            rows,
            { name: schoolName, teacher: teacherName, logo: schoolLogo, email: contactEmail, phone: contactPhone }
        );
        showSuccess("Detailed diagnostic report exported.");
    } finally {
        setIsExporting(false);
    }
  };

  const getCognitiveColor = (level?: string) => {
      switch(level) {
          case 'knowledge': return "bg-slate-100 text-slate-700";
          case 'comprehension': return "bg-blue-50 text-blue-700";
          case 'application': return "bg-green-50 text-green-700";
          case 'analysis': return "bg-purple-50 text-purple-700";
          case 'evaluation': return "bg-amber-50 text-amber-700";
          case 'creation': return "bg-red-50 text-red-700";
          default: return "bg-muted text-muted-foreground";
      }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-[95vw] w-[1200px] h-[90vh] flex flex-col p-0 overflow-hidden">
        <div className="p-6 pb-4 border-b bg-muted/20 shrink-0">
          <DialogHeader>
            <div className="flex justify-between items-start">
                <div className="space-y-1">
                    <div className="flex items-center gap-2">
                        <Badge variant="outline" className="bg-primary/5 text-primary border-primary/20 uppercase tracking-widest text-[9px] font-black">
                            Differentiated Item Analysis
                        </Badge>
                        {stats?.savedDiagnostic && (
                            <Badge variant="secondary" className="bg-green-100 text-green-700 border-none text-[9px] font-black uppercase">
                                <CheckCircle2 className="h-2.5 w-2.5 mr-1" /> Document Finalized
                            </Badge>
                        )}
                    </div>
                    <DialogTitle className="text-2xl font-bold">{assessment.title}</DialogTitle>
                    <DialogDescription>Identify skill-specific barriers and class-wide patterns.</DialogDescription>
                </div>
                <div className="flex gap-2">
                    <Button variant="outline" onClick={handleRunAI} disabled={isGeneratingAI || loading} className="gap-2 font-bold h-9 bg-purple-50 text-purple-700 border-purple-200 hover:bg-purple-100">
                        {isGeneratingAI ? <Loader2 className="h-4 w-4 animate-spin" /> : <BrainCircuit className="h-4 w-4" />}
                        Run Skill-Aware AI Analysis
                    </Button>
                    <Button variant="outline" onClick={handleSave} disabled={isSaving || loading} className="gap-2 font-bold h-9">
                        {isSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                        Save Analysis
                    </Button>
                    <Button onClick={handleActivatePlan} disabled={isActivating || rows.length === 0} className="gap-2 font-bold h-9 bg-green-600 hover:bg-green-700">
                        {isActivating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Rocket className="h-4 w-4" />}
                        Activate Action Plan
                    </Button>
                    <Button onClick={handleExport} disabled={isExporting || !stats} className="font-bold gap-2 h-9">
                        {isExporting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
                        Export PDF
                    </Button>
                </div>
            </div>
          </DialogHeader>
        </div>

        <ScrollArea className="flex-1 p-6">
          {loading ? (
            <div className="flex flex-col items-center justify-center py-20 gap-4">
                <Loader2 className="h-10 w-10 animate-spin text-primary opacity-20" />
                <p className="text-sm font-medium text-muted-foreground animate-pulse">Running skill heuristics...</p>
            </div>
          ) : stats ? (
            <div className="space-y-10 pb-10">
                <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
                    {stats.qStats.map(s => (
                        <div key={s.id} className={cn(
                            "flex flex-col p-4 rounded-xl border transition-all relative overflow-hidden",
                            s.isWeak ? "bg-red-50 border-red-100" : "bg-muted/30 border-muted-foreground/10"
                        )}>
                            <div className="flex justify-between items-start mb-2 relative z-10">
                                <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Q{s.number}</span>
                                {s.isWeak ? <AlertTriangle className="h-3 w-3 text-red-500" /> : <CheckCircle2 className="h-3 w-3 text-green-600" />}
                            </div>
                            <div className="text-2xl font-black relative z-10">{s.avg}%</div>
                            <div className="flex justify-between items-center mt-1 relative z-10">
                                <p className="text-[9px] text-muted-foreground uppercase font-bold truncate max-w-[80px]" title={s.skill}>{s.skill || "Skill"}</p>
                                <span className="text-[8px] font-black text-muted-foreground/60">{s.passRate}% Pass</span>
                            </div>
                        </div>
                    ))}
                </div>

                {/* THEMES SECTION */}
                <div className="grid md:grid-cols-2 gap-6">
                    <Card className="bg-primary/5 border-primary/20 shadow-none">
                        <CardHeader className="pb-3">
                            <CardTitle className="text-xs font-black uppercase tracking-widest flex items-center gap-2">
                                <LayoutGrid className="h-4 w-4 text-primary" /> Overall Class-Level Themes
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-2">
                            {themes.length === 0 ? (
                                <p className="text-xs text-muted-foreground italic">Run AI Analysis to detect patterns.</p>
                            ) : (
                                themes.map((theme, i) => (
                                    <div key={i} className="flex gap-2 items-start p-2 bg-background rounded border text-sm font-medium">
                                        <div className="mt-1 h-1.5 w-1.5 rounded-full bg-primary shrink-0" />
                                        <span>{theme}</span>
                                    </div>
                                ))
                            )}
                        </CardContent>
                    </Card>

                    <Card className="bg-blue-50/50 border-blue-200 shadow-none">
                        <CardHeader className="pb-3">
                            <CardTitle className="text-xs font-black uppercase tracking-widest flex items-center gap-2 text-blue-700">
                                <Lightbulb className="h-4 w-4" /> Global Remediation Strategies
                            </CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-2">
                             {overallInterventions.length === 0 ? (
                                <p className="text-xs text-muted-foreground italic text-blue-800/60">No global strategies recorded.</p>
                            ) : (
                                overallInterventions.map((int, i) => (
                                    <div key={i} className="flex gap-2 items-start p-2 bg-white rounded border border-blue-100 text-sm text-blue-900">
                                        <Check className="h-4 w-4 text-blue-600 shrink-0" />
                                        <span>{int}</span>
                                    </div>
                                ))
                            )}
                        </CardContent>
                    </Card>
                </div>

                <div className="space-y-4">
                    <div className="flex items-center gap-2">
                        <TableIcon className="h-4 w-4 text-primary" />
                        <h4 className="text-xs font-black uppercase tracking-widest text-muted-foreground">Item-Level Root Cause Analysis</h4>
                    </div>

                    <div className="border rounded-xl overflow-hidden bg-background shadow-sm">
                        <Table>
                            <TableHeader className="bg-muted/50">
                                <TableRow>
                                    <TableHead className="w-[15%] font-black text-[9px] uppercase tracking-widest py-3">Question / Skill</TableHead>
                                    <TableHead className="w-[20%] font-black text-[9px] uppercase tracking-widest py-3">Result Summary</TableHead>
                                    <TableHead className="w-[30%] font-black text-[9px] uppercase tracking-widest py-3">Specific Root Causes</TableHead>
                                    <TableHead className="w-[30%] font-black text-[9px] uppercase tracking-widest py-3">Targeted Interventions</TableHead>
                                    <TableHead className="w-[5%]"></TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {rows.map((row) => (
                                    <TableRow key={row.id} className="group hover:bg-muted/5 transition-colors align-top">
                                        <TableCell className="p-3 space-y-2">
                                            <Input 
                                                value={row.question}
                                                onChange={(e) => handleUpdateRow(row.id, 'question', e.target.value)}
                                                className="border-none shadow-none font-bold text-sm bg-transparent p-0 focus-visible:ring-0"
                                            />
                                            <Badge className={cn("text-[8px] uppercase font-black px-1.5 h-4 border-none", getCognitiveColor(row.cognitive_level))}>
                                                {row.cognitive_level || 'unknown'}
                                            </Badge>
                                        </TableCell>
                                        <TableCell className="p-3">
                                            <Textarea 
                                                value={row.performance_summary}
                                                onChange={(e) => handleUpdateRow(row.id, 'performance_summary', e.target.value)}
                                                className="border-none shadow-none resize-none bg-transparent min-h-[60px] text-xs p-0 focus-visible:ring-0"
                                            />
                                        </TableCell>
                                        <TableCell className="p-3 border-l">
                                            <Textarea 
                                                value={row.possible_root_causes.join('\n')}
                                                onChange={(e) => handleUpdateRow(row.id, 'possible_root_causes', e.target.value.split('\n'))}
                                                className="border-none shadow-none resize-none bg-transparent min-h-[100px] text-xs p-0 focus-visible:ring-0 leading-relaxed"
                                                placeholder="Enter skill-based causes..."
                                            />
                                        </TableCell>
                                        <TableCell className="p-3 border-l">
                                            <Textarea 
                                                value={row.targeted_interventions.join('\n')}
                                                onChange={(e) => handleUpdateRow(row.id, 'targeted_interventions', e.target.value.split('\n'))}
                                                className="border-none shadow-none resize-none bg-transparent min-h-[100px] text-xs p-0 focus-visible:ring-0 leading-relaxed text-blue-800 dark:text-blue-300 font-medium"
                                                placeholder="Enter actions..."
                                            />
                                        </TableCell>
                                        <TableCell className="p-2 text-right">
                                            <Button 
                                                variant="ghost" 
                                                size="icon" 
                                                className="h-7 w-7 text-muted-foreground hover:text-destructive opacity-0 group-hover:opacity-100 transition-opacity"
                                                onClick={() => handleDeleteRow(row.id)}
                                            >
                                                <Trash2 className="h-3.5 w-3.5" />
                                            </Button>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </div>
                </div>

                <div className="grid md:grid-cols-2 gap-6">
                    <div className="p-4 bg-blue-50 border border-blue-100 rounded-xl flex items-start gap-3 h-fit">
                        <Info className="h-5 w-5 text-blue-600 mt-0.5" />
                        <div className="space-y-1">
                            <p className="text-xs font-bold text-blue-900 uppercase tracking-tight">Precision Diagnostics</p>
                            <p className="text-[11px] text-blue-800 leading-tight">
                                Root causes are now generated based on cognitive demand and skill clusters. Review themes for systemic classroom barriers.
                            </p>
                        </div>
                    </div>
                    
                    <div className="p-4 bg-purple-50 border border-purple-100 rounded-xl flex items-start gap-3 h-fit">
                        <Rocket className="h-5 w-5 text-purple-600 mt-0.5" />
                        <div className="space-y-1">
                            <p className="text-xs font-bold text-purple-900 uppercase tracking-tight">Audit Trail Ready</p>
                            <p className="text-[11px] text-purple-800 leading-tight">
                                Themes and interventions detected here are automatically bridged to your Remediation Action Plan for official record keeping.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
          ) : null}
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
};